from .about import AboutHandler
from .app import AppHandler
from .features import FeaturesHandler
from .home import HomeHandler
from .login import LoginHandler
from .register import RegisterHandler
from .thankyou import ThankyouHandler
from .organisation import OrganisationHandler
from .user_login import UserLoginHandler